application: heroku-logs
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /syslog/.*
  script: bin/loghandler.php
  
- url: /api/summary
  script: bin/summary.php
  login: admin
  
- url: /api/.*
  script: bin/apihandler.php
  login: required
  auth_fail_action: unauthorized

- url: /init
  script: bin/init.php

- url: /
  static_files: web/landing.html
  upload: web/landing.html
  
- url: /app/
  static_files: web/app.html
  upload: web/app.html
  login: required
  
- url: /assets
  static_dir: web/assets
